### ISSUE TITLE
Experimental push on scalar is now forbidden at /usr/local/bin/indent2tree line 43, near "};"

### ISSUE THREAD

**Issue by MountainX** [bAndie91/tools#3]
Experimental push on scalar is now forbidden at /usr/local/bin/indent2tree line 43, near "};"

Relevant?
https://stackoverflow.com/a/41192741

**Comment by ikegami** [comment]
push $ForkPoint->{subtree}, ...

should be

    push @{ $ForkPoint->{subtree} }, ...

**Comment by MountainX** [comment]
This resolves it for me. Thank you.

**Comment by MountainX** [comment]
Thank you. It is working for me now.
